export const AgentWalletABI = [
  { "type": "function", "name": "approveERC20", "inputs": [{ "name": "token", "type": "address" }, { "name": "spender", "type": "address" }, { "name": "amount", "type": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "dailyEthLimit", "inputs": [], "outputs": [{ "name": "", "type": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "depositETH", "inputs": [], "outputs": [], "stateMutability": "payable" },
  { "type": "function", "name": "ethSpentToday", "inputs": [], "outputs": [{ "name": "", "type": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "executeContractCall", "inputs": [{ "name": "target", "type": "address" }, { "name": "ethValue", "type": "uint256" }, { "name": "data", "type": "bytes" }], "outputs": [{ "name": "result", "type": "bytes" }], "stateMutability": "nonpayable" },
  { "type": "function", "name": "executeERC20Transfer", "inputs": [{ "name": "token", "type": "address" }, { "name": "to", "type": "address" }, { "name": "amount", "type": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "executeETH", "inputs": [{ "name": "target", "type": "address" }, { "name": "amount", "type": "uint256" }, { "name": "data", "type": "bytes" }], "outputs": [{ "name": "result", "type": "bytes" }], "stateMutability": "nonpayable" },
  { "type": "function", "name": "executor", "inputs": [], "outputs": [{ "name": "", "type": "address" }], "stateMutability": "view" },
  { "type": "function", "name": "factory", "inputs": [], "outputs": [{ "name": "", "type": "address" }], "stateMutability": "view" },
  { "type": "function", "name": "getEthBalance", "inputs": [], "outputs": [{ "name": "", "type": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "getTokenBalance", "inputs": [{ "name": "token", "type": "address" }], "outputs": [{ "name": "", "type": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "initialize", "inputs": [{ "name": "_owner", "type": "address" }, { "name": "_executor", "type": "address" }, { "name": "_dailyEthLimit", "type": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "initialized", "inputs": [], "outputs": [{ "name": "", "type": "bool" }], "stateMutability": "view" },
  { "type": "function", "name": "owner", "inputs": [], "outputs": [{ "name": "", "type": "address" }], "stateMutability": "view" },
  { "type": "function", "name": "pauseWallet", "inputs": [], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "unpauseWallet", "inputs": [], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "updateDailyEthLimit", "inputs": [{ "name": "newLimit", "type": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "updateExecutor", "inputs": [{ "name": "newExecutor", "type": "address" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "walletPaused", "inputs": [], "outputs": [{ "name": "", "type": "bool" }], "stateMutability": "view" },
  { "type": "function", "name": "withdrawETH", "inputs": [{ "name": "amount", "type": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "withdrawERC20", "inputs": [{ "name": "token", "type": "address" }, { "name": "amount", "type": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "event", "name": "DepositETH", "inputs": [{ "name": "from", "type": "address", "indexed": true }, { "name": "amount", "type": "uint256", "indexed": false }], "anonymous": false },
  { "type": "event", "name": "WithdrawETH", "inputs": [{ "name": "to", "type": "address", "indexed": true }, { "name": "amount", "type": "uint256", "indexed": false }], "anonymous": false },
  { "type": "event", "name": "Initialized", "inputs": [{ "name": "owner", "type": "address", "indexed": true }, { "name": "executor", "type": "address", "indexed": true }], "anonymous": false },
  { "type": "receive", "stateMutability": "payable" }
] as const;
